### PR TITLE
#136: Fixed switching the source schema

### LINKED ISSUE #136: Updating SCHEMA_NAME does not refresh metadata
## Situation

When updating the `SCHEMA_NAME` with this command:

```sql
ALTER VIRTUAL SCHEMA virtual_schema SET SCHEMA_NAME='SCHEMA_B'
```

the adapter does not refresh the metadata.

After receiving request

```json
{
	"properties" : 
	{
		"SCHEMA_NAME" : "SCHEMA_SET_PROPS_B"
	},
	"schemaMetadataInfo" : 
	{
		"adapterNotes" : "T:---",
		"name" : "SCHEMA_SET_PROPS_A_RLS",
		"properties" : 
		{
			"DEBUG_ADDRESS" : "10.181.181.168:3000",
			"LOG_LEVEL" : "TRACE",
			"SCHEMA_NAME" : "SCHEMA_SET_PROPS_A"
		}
	},
	"type" : "setProperties"
}
```

the adapter replies with

```
{"schemaMetadata":{"tables":[{"name":"T","columns":[{"name":"C1","dataType":{"type":"VARCHAR","characterSet":"UTF8","size":10}}]}],"adapterNotes":"T:---"},"type":"setProperties"}
```

But the response contains the data types of the previous schema `SCHEMA_SET_PROPS_A`.

With Exasol 7.1 this was not a problem but in Exasol 8 querying the virtual schema fails:

```
java.sql.SQLException: Adapter generated invalid pushdown query for virtual table T: Data type mismatch in column number 1 (1-indexed).Expected VARCHAR(10) UTF8, but got DATE. (pushdown query: SELECT * FROM "SCHEMA_SET_PROPS_B"."T") (Session: 1771195594457219072)
```

## Solution
The adapter must refresh the metadata when receiving a `setProperties` request. The implementation could be similar as in [exasol-virtual-schema-lua](https://github.com/exasol/exasol-virtual-schema-lua/).

### PR DESCRIPTION
**Pull request by redcatbear**
Closes #136.

### CODE REVIEW

File: src/test/java/com/exasol/AbstractLuaVirtualSchemaIT.java [hunk 1]
```diff
@@ -85,7 +86,17 @@ protected VirtualSchema createVirtualSchema(final Schema sourceSchema, final Map
...
     protected VirtualSchema createVirtualSchema(final Schema sourceSchema) {
-        return createVirtualSchema(sourceSchema, Collections.emptyMap());
+        return createVirtualSchema(sourceSchema, getDebugProperties());
+    }
+
+    private Map<String, String> getDebugProperties() {
+        final String debugHost = System.getProperty("com.exasol.log.host");
+        if(debugHost == null)
+            return Collections.emptyMap();
+        else {
```
Comment (kaklakariada) [inline src/test/java/com/exasol/AbstractLuaVirtualSchemaIT.java:96]:
```suggestion
        if(debugHost == null) {
            return Collections.emptyMap();
        } else {
```

File: src/test/java/com/exasol/MetadataReadingIT.java [hunk 2]
```diff
@@ -196,6 +196,30 @@ private void execute(final String sql) throws SQLException {
...
+                expectRows("D", "DATE"));
+    }
+
+    private void replaceSourceSchema(final VirtualSchema virtualSchema, final Schema sourceSchema) {
+        final String sql = "ALTER VIRTUAL SCHEMA " + virtualSchema.getFullyQualifiedName() + " SET SCHEMA_NAME='" +
+                sourceSchema.getName() + "'";
+        try {
+            execute(sql);
+        } catch (final SQLException exception) {
+            throw new AssertionError("Unable to replace source schemaa using query '" + sql + "'", exception);
```
Comment (kaklakariada) [inline src/test/java/com/exasol/MetadataReadingIT.java:219]:
```suggestion
            throw new AssertionError("Unable to replace source schema using query '" + sql + "'", exception);
```

Comment (kaklakariada) [reply src/test/java/com/exasol/MetadataReadingIT.java:219]: In general: would it make sense to move exception handling to the `execute()` method, i.e.
* catch `SQLException` in `execute()`
* throw new exception incl. the executed sql statement

**Review by kaklakariada — CHANGES_REQUESTED** [review]

File: doc/changes/changes_1.5.1.md [hunk 3]
```diff
@@ -1,13 +1,16 @@
 # Exasol Row Level Security (Lua) 1.5.1, released 2023-10-25
```
Comment (kaklakariada) [inline doc/changes/changes_1.5.1.md:1]:
```suggestion
# Exasol Row Level Security (Lua) 1.5.1, released 2023-10-26
```

**Review by kaklakariada — CHANGES_REQUESTED** [review]

**Review by kaklakariada — APPROVED** [review]
